server:
  port: 8087

spring:
  application:
    name: auth-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${BASE_URL}/auth/realms/boolkus
          jwk-set-uri: http://keycloak:8080/realms/boolkus/protocol/openid-connect/certs
keycloak:
  auth-server-url: http://keycloak:8080
  realm: boolkus
  resource: auth-service
  credentials:
    secret: gkaUiQqNvIPpS45UQYl2XwZQoqidvaa7