server:
  port: 8087

spring:
  application:
    name: auth-service

keycloak:
  auth-server-url: http://bks-keycloak:8080
  realm: boolkus
  resource: user-manager
  credentials:
    secret: gkaUiQqNvIPpS45UQYl2XwZQoqidvaa7