server:
  port: 8081
yandex:
  dictionary:
    api:
      uri: https://dictionary.yandex.net/api/v1
      key: ${YANDEX_DICT_API_KEY}
      lang: en-ru
spring:
  application:
    name: translation-service
  cache:
    type: redis
    redis:
      time-to-live: 86400000
  data:
    redis:
      host: translation-service-cache
      port: 6379
      password: ${TRANSLATION_SERVICE_CACHE_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${BASE_URL}/auth/realms/boolkus
          jwk-set-uri: http://keycloak:8080/realms/boolkus/protocol/openid-connect/certs

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus
  endpoint:
    health:
      show-details: always
  zipkin:
    tracing:
      endpoint: http://tempo:9411/api/v2/spans
  tracing:
    sampling:
      probability: 0.3
loki:
  url: http://loki:3100