name: parallel-reading
services:
  # Infrastructure
  bks-keycloak:
    image: quay.io/keycloak/keycloak:26.2
    container_name: bks-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - './config/keycloak/import:/opt/keycloak/data/import'
    ports:
      - '8082:8080'
    command: start-dev --import-realm
    networks:
      - boolkus-net

  bks-minio:
    image: minio/minio
    container_name: bks-minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - boolkus-net

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092 # исправить на kafka
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    volumes:
      - kafka_data:/bitnami/kafka
    networks:
      - boolkus-net

  nginx:
    container_name: nginx
    build:
      context: ./config/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - boolkus-net
    depends_on:
      - bks-minio
      - bks-keycloak

  bks-books-db:
    image: postgres:16
    container_name: bks-books-db
    environment:
      POSTGRES_DB: books-db
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - books_db_data:/var/lib/postgresql/data
    networks:
      - boolkus-net

  books-service-cache:
    image: redis:latest
    container_name: books-service-cache
    command: redis-server --requirepass password
    environment:
      REDIS_PASSWORD: password
    ports:
      - "6379:6379"
    networks:
      - boolkus-net

  translation-service-cache:
    image: redis:latest
    container_name: translation-service-cache
    command: redis-server --requirepass password
    environment:
      REDIS_PASSWORD: password
    ports:
      - "6380:6379"
    networks:
      - boolkus-net

  bks-dictionary-db:
    image: postgres:16
    container_name: bks-dictionary-db
    environment:
      POSTGRES_DB: dictionary-db
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - dictionary_db_data:/var/lib/postgresql/data
    networks:
      - boolkus-net

  # Services
  book-service:
    restart: on-failure
    build:
      dockerfile: Dockerfile
      args:
        JAR_FILE: book-service/target/*-exec.jar
    networks:
      - boolkus-net
    depends_on:
      - bks-books-db
      - bks-keycloak
      - books-service-cache

  book-upload-service:
    restart: on-failure
    build:
      dockerfile: Dockerfile
      args:
        JAR_FILE: book-upload-service/target/*-exec.jar
    networks:
      - boolkus-net
    depends_on:
      - kafka
      - bks-minio

  dictionary-service:
    restart: on-failure
    build:
      dockerfile: Dockerfile
      args:
        JAR_FILE: dictionary-service/target/*-exec.jar
    networks:
      - boolkus-net
    depends_on:
      - bks-dictionary-db
      - bks-keycloak

  translation-service:
    restart: on-failure
    build:
      dockerfile: Dockerfile
      args:
        JAR_FILE: translation-service/target/*-exec.jar
    networks:
      - boolkus-net
    depends_on:
      - translation-service-cache
      - bks-keycloak

  admin-client:
    restart: on-failure
    build:
      dockerfile: Dockerfile
      args:
        JAR_FILE: admin-client/target/*-exec.jar
    networks:
      - boolkus-net
    depends_on:
      - bks-keycloak
      - bks-minio
      - kafka

  auth-service:
    restart: on-failure
    build:
      dockerfile: Dockerfile
      args:
        JAR_FILE: auth-service/target/*-exec.jar
    networks:
      - boolkus-net
    depends_on:
      - bks-keycloak

volumes:
  minio_data:
  kafka_data:
  books_db_data:
  dictionary_db_data:

networks:
  boolkus-net: 
    driver: bridge