server:
  port: 8085

spring:
  application:
    name: dictionary-service
  datasource:
    url: jdbc:postgresql://dictionary-db:5432/dictionary-db
    username: username
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/boolkus/protocol/openid-connect/certs