server:
  port: 8080

spring:
  application:
    name: books-service
  datasource:
    url: jdbc:postgresql://localhost:5433/books-db
    username: username
    password: password
  cache:
    type: redis
    redis:
      time-to-live: 86400000
  data:
    redis:
      host: localhost
      port: 6379
      password: password
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/boolkus