server:
  port: 8080

spring:
  application:
    name: books-service
  datasource:
    url: jdbc:postgresql://localhost:5433/books-db
    username: username
    password: password
  cache:
    type: redis
    cache-names: redis-cache
  data:
    redis:
      host: localhost
      port: 6379
      password: password