server:
  port: 8080
spring:
  application:
    name: books-service
  datasource:
    url: jdbc:postgresql://books-db:5432/books-db
    username: username
    password: ${BOOKS_DB_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  cache:
    type: redis
    redis:
      time-to-live: 86400000
  data:
    redis:
      host: books-service-cache
      port: 6379
      password: ${BOOKS_SERVICE_CACHE_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${BASE_URL}/auth/realms/boolkus
          jwk-set-uri: http://keycloak:8080/realms/boolkus/protocol/openid-connect/certs
  kafka:
    bootstrap-servers: kafka:9094
    consumer:
      group-id: ${spring.application.name}-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus
  endpoint:
    health:
      show-details: always