server:
  port: 8083

services:
  books:
    uri: http://localhost:8080
    registration-id: keycloak

spring:
  application:
    name: admin-client
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/boolkus
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: admin-app
            client-secret: drHE0eBoRAENaroK59E993VqfSp9pham
            scope:
              - openid
              - microprofile-jwt
              - view_books
              - edit_books
minio:
  url: http://localhost:9000
  access-key: admin
  secret-key: password
  bucket: covers
