server:
  port: 8083

services:
  books:
    uri: http://localhost:8080
    registration-id: keycloak

spring:
  application:
    name: admin-client
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/boolkus
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: admin-app
            client-secret: drHE0eBoRAENaroK59E993VqfSp9pham
            scope:
              - openid
              - microprofile-jwt
              - view_books
              - edit_books
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${spring.application.name}-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
minio:
  url: http://localhost:9000
  access-key: admin
  secret-key: password
  bucket: covers
