name: maven-build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["main"]

jobs:
  checkstyle:
    runs-on: ubuntu 22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ hasFiles(**/pom.xml)}}
          restore-keys: |
            maven-
      - run: mvn clean install