datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    version: 1
    jsonData:
      maxLines: 1000
      queryTimeout: 30s

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    version: 1

  - name: Victoria-Metrics
    type: prometheus
    access: proxy
    url: http://victoria-metrics:8428
    version: 1